title: "Hello!, i'm David"
description: "Portfolio"
url: "https://DVDGNM99.github.io"
baseurl: ""

theme: minima
minima:
  skin: classic      # o 'dark' se vuoi base scura
  social_links:
    - { platform: github,   user_url: "https://github.com/DVDGNM99" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/david-ganem-535769171/" }

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

author:
  name: "David Ganem"
  email: "ganem.david@gmail.com"
